/*********Author : Khalid Mosaad Zakaria */

/*********Date   :   20/4/2021          */

/*********Version: 2                     */
/****************Desc: *******************/
#include"BIT_Math.h"
#include"STD_Types.h"
#include"ADC_interface.h"
#include"ADC_private.h"
#include"ADC_config.h"
#include"DIO_interface.h"


u8 SPCR_Help;

void GIE_voidEnable(void)
{
	// GIE
	SET_BIT(SREG,GIE);
}

void GIE_voidDisable(void)
{
	// GIE
	CLR_BIT(SREG,GIE);
}

void ADC_VoidInit(void)
{
	
	#if VREF_S==ACCC_PIN 
		CLR_BIT(ADMUX,REFS1);
		CLR_BIT(ADMUX,REFS0);
	#elif VREF_S==ACCC_PIN_SAMEVCC
		CLR_BIT(ADMUX,REFS1);		
		SET_BIT(ADMUX,REFS0);		
	#elif VREF_S== RESERVED
		SET_BIT(ADMUX,REFS1);
		CLR_BIT(ADMUX,REFS0);
	#elif VREF_S==INTERNAL_2_56
		SET_BIT(ADMUX,REFS1);
		SET_BIT(ADMUX,REFS0);
	#endif

	#if ADC_DATA_ADJUST==ADJUST_RIGHT
		CLR_BIT(ADMUX,ADLAR);
	#elif ADC_DATA_ADJUST==ADJUST_LEFT		
		SET_BIT(ADMUX,ADLAR);		
	#endif

	#if INT_OP == DISABLE
		CLR_BIT(ADCSRA,ADIE);
	#elif INT_OP == ENABLE	
		GIE_voidEnable();	
		SET_BIT(ADCSRA,ADIE);		
	#endif
	
	#if ADC_CHANNEL == ADC_C0
		CLR_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL == ADC_C1
		SET_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);	
		CLR_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);	
	#elif ADC_CHANNEL == ADC_C2
		CLR_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL == ADC_C3
		SET_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL == ADC_C4
		CLR_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);	
		SET_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);	
	#elif ADC_CHANNEL == ADC_C5
		SET_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		SET_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL == ADC_C6
		CLR_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);	
		SET_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL == ADC_C7
		SET_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		SET_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC0_ADC0_10X 
		CLR_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC1_ADC0_10X 
		SET_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC0_ADC0_200X
		CLR_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC1_ADC0_200X
		SET_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC2_ADC2_10X 
		CLR_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		SET_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC3_ADC2_10X 
		SET_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		SET_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC2_ADC2_200X
		CLR_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		SET_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC3_ADC2_200X
		SET_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		SET_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC0_ADC1_1x  
		CLR_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC1_ADC1_1x 
		SET_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC2_ADC1_1x  
		CLR_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC3_ADC1_1x  
		SET_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC4_ADC1_1x 
		CLR_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		SET_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC5_ADC1_1x 
		SET_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		SET_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC6_ADC1_1x 
		CLR_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		SET_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC7_ADC1_1x  
		SET_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		SET_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC0_ADC2_1x  
		CLR_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC1_ADC2_1x 
		SET_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC2_ADC2_1x  
		CLR_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC3_ADC2_1x 
		SET_BIT(ADMUX,MUX0);
		SET_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC4_ADC2_1x 
		CLR_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		SET_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#elif ADC_CHANNEL==ADC5_ADC2_1x 
		SET_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		SET_BIT(ADMUX,MUX2);
		SET_BIT(ADMUX,MUX3);
		SET_BIT(ADMUX,MUX4);
	#endif
	#if	CLOCK_RATE == F_2
		SET_BIT(ADCSRA,ADPS0);
		CLR_BIT(ADCSRA,ADPS1);
		CLR_BIT(ADCSRA,ADPS2);
		
	#elif CLOCK_RATE== F_4
		CLR_BIT(ADCSRA,ADPS0);
		SET_BIT(ADCSRA,ADPS1);
		CLR_BIT(ADCSRA,ADPS2);
	#elif CLOCK_RATE== F_8
		SET_BIT(ADCSRA,ADPS0);
		SET_BIT(ADCSRA,ADPS1);
		CLR_BIT(ADCSRA,ADPS2);
	#elif CLOCK_RATE== F_16
		CLR_BIT(ADCSRA,ADPS0);
		CLR_BIT(ADCSRA,ADPS1);
		SET_BIT(ADCSRA,ADPS2);

	#elif	CLOCK_RATE == F_32
		SET_BIT(ADCSRA,ADPS0);
		CLR_BIT(ADCSRA,ADPS1);
		SET_BIT(ADCSRA,ADPS2);
		
	#elif CLOCK_RATE== F_64
		CLR_BIT(ADCSRA,ADPS0);
		SET_BIT(ADCSRA,ADPS1);
		SET_BIT(ADCSRA,ADPS2);
	#elif CLOCK_RATE== F_128
		SET_BIT(ADCSRA,ADPS0);
		SET_BIT(ADCSRA,ADPS1);
		SET_BIT(ADCSRA,ADPS2);
	#endif

	


}

void ADC_VoidSelect_channel(u8 Copy_Channel)
{
	CLR_BIT(ADMUX,MUX4);
	CLR_BIT(ADMUX,MUX3);


	switch(Copy_Channel)
	{	case ADC_C0 : ADMUX&=0B11100000; break;  // choose channel
		case ADC_C1 :SET_BIT(ADMUX,MUX0);CLR_BIT(ADMUX,MUX1);CLR_BIT(ADMUX,MUX2); break;
		case ADC_C2 :CLR_BIT(ADMUX,MUX0);SET_BIT(ADMUX,MUX1);CLR_BIT(ADMUX,MUX2); break;
		case ADC_C3 :CLR_BIT(ADMUX,MUX0);SET_BIT(ADMUX,MUX1);SET_BIT(ADMUX,MUX2); break;
		case ADC_C4 :SET_BIT(ADMUX,MUX0);CLR_BIT(ADMUX,MUX1);CLR_BIT(ADMUX,MUX2); break;
		case ADC_C5 :SET_BIT(ADMUX,MUX0);CLR_BIT(ADMUX,MUX1);SET_BIT(ADMUX,MUX2); break;
		case ADC_C6 :SET_BIT(ADMUX,MUX0);SET_BIT(ADMUX,MUX1);CLR_BIT(ADMUX,MUX2); break;
		case ADC_C7 :SET_BIT(ADMUX,MUX0);SET_BIT(ADMUX,MUX1);SET_BIT(ADMUX,MUX2); break;
	}
}

void ADC_VoidADCEnable(void)
{
	SET_BIT(ADCSRA,ADEN);
}

void ADC_VoidStartConversion(void)
{
	SET_BIT(ADCSRA,ADSC);
}
u16 ADC_U16ReadDigitalValue(void)
{	ADC_VoidStartConversion();
	while(GET_BIT(ADCSRA,ADIF) == 0);
	return ADC_DATA;
}

void __vector_16(void )
{
// write your code 

}
